=== Shubhy9399/TechmentTraning2020/Day15/studentstructure.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT students (student+)>
<!ELEMENT student (name,rollno)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT rollno (#PCDATA)>

=== Shubhy9399/TechmentTraning2020/Day15/student.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE students SYSTEM "studentstructure.dtd">
<students>

  <student>
  <name>Rina</name>
  <rollno>25</rollno>
  </student>
  
  <student>
   <name>Rahul</name>
  <rollno>23</rollno>
  </student>
  
   <student>
   <name>Seema</name>
   <rollno>24</rollno>
  </student>
  
</students>
